# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "kafka-streams" do |streams|
    streams.vm.network "private_network", ip: "192.168.50.10" 

    streams.vm.provision "shell", inline: "sudo yum install wget -y"
    streams.vm.provision "shell", path: "scripts/java.sh"
    streams.vm.provision "shell", path: "scripts/kafka-streams.sh"
  end
end